#!/bin/bash
NEWUSER=chef
sudo useradd -m ${NEWUSER} -s /bin/bash -G sudo
U=`umask`
umask 0226
sudo echo "${NEWUSER} ALL=(ALL) NOPASSWD: ALL" |sudo tee /etc/sudoers.d/${NEWUSER} > /dev/null
umask $U
sudo apt-get update -q
sudo apt-get install -q -y git-core
sudo su - ${NEWUSER} -c "git clone https://github.com/Synchro/catering-college ; cd catering-college ; ./install-chef-server"
sudo rm /etc/sudoers.d/${NEWUSER}